### ISSUE TITLE
Should ODC update the database if we get the same datum again?

### ISSUE THREAD

**Issue by ryukzak** [mlabs-haskell/ogmios-datum-cache#108]
Currently: `INSERT INTO datums (hash, value) (SELECT h::text, v::bytea FROM unnest($1, $2) AS x(h, v)) ON CONFLICT DO NOTHING`

So, if a user would like to fetch datums again (e.g., the database is corrupted), the user should manually clean the database before. Maybe rewriting data is more expected behaviour.

**Comment by Luis-omega** [comment]
What about making in another cli option that is mandatory?

**Comment by t4ccer** [comment]
Yeah, I think that overriding datum with new one is more desired behavior. I don't see a reason to support current behavior as it serves no benefit.
