### ISSUE TITLE
DatumHash should be a primary key in db

### ISSUE THREAD

**Issue by t4ccer** [mlabs-haskell/ogmios-datum-cache#17]
Otherwise when requesting multiple datums one can get a response with multiple responses for one datum

**Comment by aske** [comment]
Stumbled on this issue just now -- did you mean "when requesting a single datum you can get multiple responses"? If yes -- that's handled by the unique index on the `hash` column.

**Comment by t4ccer** [comment]
We had this issue when user requested multiple datums endpoint:
```
{
  "hashes": [
    "e827cc9fab9038391dabbe6b79440d7a14c4a38de5a69b2e130acbb46b5ae6ed"
   ]
}
```
and endpoint returned multiple (same) datums with the same hash. But I am actually not sure if their database was configured by ODC itself or by hand. It should be easy to recreate

**Comment by aske** [comment]
Hm, yeah, probably that index was missing from their db.

**Comment by t4ccer** [comment]
I wasn't able to replicate it on db that was set up by ODC, feel free to open if it happens again and you are sure that db was set up by ODC and not by hand
