### ISSUE TITLE
Start block fetcher at origin

### ISSUE THREAD

**Issue by t4ccer** [mlabs-haskell/ogmios-datum-cache#39]
Add an option to start block fetcher at `origin`. Ogmios `FindIntersect` method can take `"origin"` as `points` argument. Origin is:
> The origin of the blockchain. This point is special in the sense that it doesn't point to any existing slots, but is preceding any existing other point.
~ https://ogmios.dev/api/#operation-publish-/?Local-Chain-Sync

Seems useful for setups that create new private testnets for integration tests.

**Comment by micahkendall** [comment]
Planning to jump on this issue tomorrow.
