### ISSUE TITLE
Set up make file

### ISSUE THREAD

**Issue by samuelWilliams99** [mlabs-haskell/ogmios-datum-cache#47]
Ensure we have a make file in this project following standards from other projects, with utils for building, format, lint, etc.

**Comment by ryukzak** [comment]
I will check it separated but looks like it happens by `checks` [inside flake.nix](https://github.com/mlabs-haskell/ogmios-datum-cache/blob/dbff887d14122249352c1a853be05023f64a2664/flake.nix#L65)

**Comment by samuelWilliams99** [comment]
Ah yes, just saw that, good catch

**Comment by samuelWilliams99** [comment]
@ryukzak please do unassign yourself from this ticket, I'd like Micah to handle it
