### ISSUE TITLE
Investigate `forever`

### ISSUE THREAD

**Issue by t4ccer** [mlabs-haskell/ogmios-datum-cache#57]
Should `forever` be [here](https://github.com/mlabs-haskell/ogmios-datum-cache/blob/master/src/Block/Fetch.hs#L175)? `receiveBlocksLoop` is a loop already so I'm not sure. I'll take a look next week

**Comment by ryukzak** [comment]
Looks like these forevers work in different threads:

1. (in receiveLoop) The request thread, which spamming the server with debounce delay between requests.
2. (in receiveBlocksLoop) The receive thread, which process data from WS.

For me it rise a few questions:

- What is the trigger to stop the request thread? Looks like it should work till the exception in one of the threads.
- How long debounce delay should be (currently 10 milliseconds)?
